-- =====================================================================================
-- 003 — Giochi, tentativi e punteggi (Tappa 5)
--
-- - Tutti i giochi aperti fin dalla prima sera; 3 tentativi AL GIORNO per gioco (settings.attempts_per_day),
--   che si rinnovano a mezzanotte (fuso settings.timezone). Vale il punteggio migliore.
-- - Finestra generale facoltativa: settings.games_open_from / games_open_until (null = nessun limite).
-- - Staff: tentativi illimitati, anche fuori finestra e con gioco disattivato.
-- - Il tentativo si conta all'AVVIO (start_attempt). La partita inviata (submit_score) viene ricontrollata
--   con regole fisse sulla sequenza delle azioni: impossibile → 'rejected' (esclusa), strana → 'flagged'
--   (contata ma segnalata allo staff), altrimenti 'valid'. Il quiz lo calcola solo il server.
--
-- Come applicarla: Supabase → SQL Editor → incolla tutto il file → Run. Si può rieseguire.
-- =====================================================================================

-- ---------- Impostazioni ----------

insert into public.settings (key, value) values
  ('attempts_per_day', '3'),
  ('timezone', '"Europe/Rome"'),
  ('games_open_from', 'null'),                            -- da impostare prima della sagra (es. "2026-10-17T15:00:00+02:00")
  ('games_open_until', '"2026-10-18T23:00:00+02:00"')     -- chiusura della classifica (D19)
on conflict (key) do nothing;

-- ---------- Tabelle ----------

create table if not exists public.games (
  id text primary key,
  name text not null,
  sort int not null,
  enabled boolean not null default true,   -- interruttore per lo staff
  duration_s int not null,                 -- durata massima della partita
  max_raw_score int not null               -- tetto di plausibilità (da app/src/games/*/scoring.js)
);
insert into public.games (id, name, sort, duration_s, max_raw_score) values
  ('acchiappa', 'Acchiappa il porcino', 1, 60, 16200),
  ('quiz', 'Quiz', 2, 100, 1000),
  ('cadono', 'Porcini che cadono', 3, 60, 4770),
  ('memory', 'Memory Torchiati', 4, 120, 1000)
on conflict (id) do update set name = excluded.name, sort = excluded.sort,
  duration_s = excluded.duration_s, max_raw_score = excluded.max_raw_score;  -- "enabled" non si tocca

create table if not exists public.quiz_questions (
  id int generated by default as identity primary key,
  text text not null,
  options text[] not null check (array_length(options, 1) = 4),
  correct_index int not null check (correct_index between 0 and 3),
  active boolean not null default true
);

create table if not exists public.attempts (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.players (id) on delete cascade,
  game_id text not null references public.games (id),
  day date not null,                        -- giorno (ora italiana) in cui è iniziato: 3 tentativi per giorno
  started_at timestamptz not null default now(),
  seed bigint not null,
  quiz_question_ids int[],
  submitted_at timestamptz,
  client_score int,                         -- punteggio dichiarato dal telefono
  raw_score int,                            -- punteggio ricalcolato dal server (quello che conta)
  stats jsonb,
  actions jsonb,
  status text not null default 'pending' check (status in ('pending', 'valid', 'flagged', 'rejected')),
  check_notes text[] not null default '{}'  -- motivi di esclusione/segnalazione, per lo staff
);
create index if not exists attempts_player_game_day_idx on public.attempts (player_id, game_id, day);
create index if not exists attempts_game_status_idx on public.attempts (game_id, status);

alter table public.games enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.attempts enable row level security;
revoke all on public.games, public.quiz_questions, public.attempts from anon, authenticated;

-- ---------- Funzioni interne ----------

create or replace function public._setting(p_key text)
returns jsonb language sql stable set search_path = public as $$
  select value from settings where key = p_key;
$$;

-- Giorno di oggi nel fuso della sagra
create or replace function public._today()
returns date language sql stable set search_path = public as $$
  select (now() at time zone coalesce(_setting('timezone') #>> '{}', 'Europe/Rome'))::date;
$$;

-- 'not_yet' | 'open' | 'closed' secondo la finestra generale
create or replace function public._window_state()
returns text language plpgsql stable set search_path = public as $$
declare
  v_from timestamptz := (_setting('games_open_from') #>> '{}')::timestamptz;
  v_until timestamptz := (_setting('games_open_until') #>> '{}')::timestamptz;
begin
  if v_from is not null and now() < v_from then return 'not_yet'; end if;
  if v_until is not null and now() >= v_until then return 'closed'; end if;
  return 'open';
end;
$$;

create or replace function public._attempts_per_day()
returns int language sql stable set search_path = public as $$
  select coalesce((_setting('attempts_per_day') #>> '{}')::int, 3);
$$;

-- Moltiplicatore di Acchiappa (come app/src/games/acchiappa/config.js)
create or replace function public._acchiappa_multiplier(p_streak int)
returns int language sql immutable as $$
  select case when p_streak >= 20 then 4 when p_streak >= 10 then 3 when p_streak >= 5 then 2 else 1 end;
$$;

-- Controlli di una partita inviata. Restituisce { status, score, notes[], correct? }.
create or replace function public._check_attempt(p_attempt attempts, p_game games, p_raw int, p_stats jsonb, p_actions jsonb)
returns jsonb language plpgsql stable set search_path = public as $$
declare
  v_notes text[] := '{}';
  v_rejected boolean := false;
  v_flagged boolean := false;
  v_score int := 0;
  v_correct int;
  v_dur int := (p_stats ->> 'durationMs')::int;
  v_elapsed_ms numeric := extract(epoch from (now() - p_attempt.started_at)) * 1000;
  v_row jsonb;
  -- Acchiappa
  v_streak int := 0; v_good int := 0; v_fast int := 0; v_taps int := 0;
  v_prev_ms int; v_int_n int := 0; v_int_sum numeric := 0; v_int_sq numeric := 0; v_std numeric;
  -- Porcini che cadono
  v_lives int := 3; v_catches int := 0; v_precise int := 0;
  -- Memory
  v_moves int := 0; v_pairs int := 0; v_last_match_ms int; v_seconds numeric; v_extra int;
  -- Quiz
  v_answer jsonb; v_q quiz_questions; v_ms int; v_seen int[] := '{}'; v_all_fast boolean := true; v_answered int := 0; v_sum_ms int := 0;
begin
  if p_actions is null or jsonb_typeof(p_actions) <> 'array' then
    return jsonb_build_object('status', 'rejected', 'score', 0, 'notes', array['azioni_mancanti']);
  end if;
  if jsonb_array_length(p_actions) > 6000 then
    return jsonb_build_object('status', 'rejected', 'score', 0, 'notes', array['troppe_azioni']);
  end if;
  if v_dur is null or v_dur < 0 then
    return jsonb_build_object('status', 'rejected', 'score', 0, 'notes', array['durata_mancante']);
  end if;
  if now() > p_attempt.started_at + interval '6 hours' then
    v_rejected := true; v_notes := array_append(v_notes, 'inviata_dopo_6_ore');
  end if;
  -- Il tempo di gioco non può superare il tempo reale passato dall'avvio
  if v_dur > v_elapsed_ms + 2000 then
    v_rejected := true; v_notes := array_append(v_notes, 'piu_veloce_dell_orologio');
  end if;
  if p_game.id <> 'quiz' and v_dur > p_game.duration_s * 1000 + 3000 then
    v_rejected := true; v_notes := array_append(v_notes, 'durata_troppo_lunga');
  end if;

  if p_game.id = 'acchiappa' then
    -- [ms, 'tap', x, y, esito, tipo, età_ms, dimensione, distanza]
    for v_row in select value from jsonb_array_elements(p_actions) loop
      continue when v_row ->> 1 <> 'tap';
      if (v_row ->> 0)::int > p_game.duration_s * 1000 + 500 then
        v_rejected := true; v_notes := array_append(v_notes, 'tocco_oltre_la_fine');
      end if;
      if v_row ->> 4 = 'good' then
        v_score := v_score + 10 * _acchiappa_multiplier(v_streak);
        v_streak := v_streak + 1;
        v_good := v_good + 1;
        if (v_row ->> 6)::int < 150 then v_fast := v_fast + 1; end if;
      elsif v_row ->> 4 = 'bad' then
        v_streak := 0;
      end if;
      if v_row ->> 4 in ('good', 'bad') then
        v_taps := v_taps + 1;
        if v_prev_ms is not null then
          v_int_n := v_int_n + 1;
          v_int_sum := v_int_sum + ((v_row ->> 0)::int - v_prev_ms);
          v_int_sq := v_int_sq + ((v_row ->> 0)::int - v_prev_ms) ^ 2;
        end if;
        v_prev_ms := (v_row ->> 0)::int;
      end if;
    end loop;
    if v_dur < p_game.duration_s * 1000 - 1000 then
      v_rejected := true; v_notes := array_append(v_notes, 'partita_troppo_corta');
    end if;
    if v_good >= 10 and v_fast > v_good * 0.2 then
      v_flagged := true; v_notes := array_append(v_notes, 'reazioni_troppo_rapide');
    end if;
    if v_int_n >= 20 then
      v_std := sqrt(greatest(0, v_int_sq / v_int_n - (v_int_sum / v_int_n) ^ 2));
      if v_std < 35 then v_flagged := true; v_notes := array_append(v_notes, 'tocchi_troppo_regolari'); end if;
    end if;

  elsif p_game.id = 'cadono' then
    -- [ms, 'catch', tipo, x_elemento, x_cestino]
    for v_row in select value from jsonb_array_elements(p_actions) loop
      continue when v_row ->> 1 <> 'catch';
      v_catches := v_catches + 1;
      if abs((v_row ->> 3)::numeric - (v_row ->> 4)::numeric) <= 1 then v_precise := v_precise + 1; end if;
      if v_row ->> 2 = 'porcino' then v_score := v_score + 10;
      elsif v_row ->> 2 = 'golden' then v_score := v_score + 50;
      elsif v_row ->> 2 = 'bomb' then v_lives := v_lives - 1;
      end if;
    end loop;
    -- Bonus sopravvivenza: arrivati alla fine del minuto con vite rimaste
    if v_lives > 0 and v_dur >= p_game.duration_s * 1000 - 1000 then
      v_score := v_score + v_lives * 50;
    elsif v_lives > 0 then
      v_rejected := true; v_notes := array_append(v_notes, 'finita_prima_con_vite');
    end if;
    if v_catches >= 20 and v_precise > v_catches * 0.8 then
      v_flagged := true; v_notes := array_append(v_notes, 'prese_troppo_precise');
    end if;

  elsif p_game.id = 'memory' then
    -- [ms, 'flip', indice, id_carta, esito]
    for v_row in select value from jsonb_array_elements(p_actions) loop
      continue when v_row ->> 1 <> 'flip';
      if v_row ->> 4 = 'match' then
        v_pairs := v_pairs + 1; v_moves := v_moves + 1; v_last_match_ms := (v_row ->> 0)::int;
      elsif v_row ->> 4 = 'mismatch' then
        v_moves := v_moves + 1;
      end if;
    end loop;
    if v_pairs > 8 then
      v_rejected := true; v_notes := array_append(v_notes, 'troppe_coppie');
    elsif v_pairs = 8 then
      v_seconds := round(v_last_match_ms / 100.0) / 10;
      v_extra := greatest(0, v_moves - 8);
      v_score := greatest(300, round(1000 - 3 * v_seconds - 20 * v_extra)::int);
      if v_seconds < 5 then v_rejected := true; v_notes := array_append(v_notes, 'troppo_veloce'); end if;
      if v_moves = 8 then v_flagged := true; v_notes := array_append(v_notes, 'memory_perfetto'); end if;
    else
      v_score := 30 * v_pairs;
    end if;

  elsif p_game.id = 'quiz' then
    -- Punteggio calcolato SOLO qui, dalle risposte: stats.answers = [{questionId, choice, ms}]
    v_correct := 0;
    for v_answer in select value from jsonb_array_elements(coalesce(p_stats -> 'answers', '[]'::jsonb)) loop
      select * into v_q from quiz_questions
      where id = (v_answer ->> 'questionId')::int and id = any (p_attempt.quiz_question_ids);
      if v_q.id is null or v_q.id = any (v_seen) then
        v_rejected := true; v_notes := array_append(v_notes, 'domanda_non_prevista');
        continue;
      end if;
      v_seen := v_seen || v_q.id;
      v_ms := least(greatest(coalesce((v_answer ->> 'ms')::int, 20000), 0), 20000);
      v_sum_ms := v_sum_ms + v_ms;
      if v_answer ->> 'choice' is not null then
        v_answered := v_answered + 1;
        if v_ms >= 800 then v_all_fast := false; end if;
      end if;
      if (v_answer ->> 'choice')::int = v_q.correct_index then
        v_correct := v_correct + 1;
        v_score := v_score + 150 + round(50 * (1 - v_ms / 20000.0))::int;
      end if;
    end loop;
    if v_sum_ms > v_elapsed_ms + 3000 then
      v_rejected := true; v_notes := array_append(v_notes, 'piu_veloce_dell_orologio');
    end if;
    if v_answered >= 4 and v_all_fast and v_correct >= 4 then
      v_flagged := true; v_notes := array_append(v_notes, 'risposte_troppo_rapide');
    end if;
  end if;

  -- Il punteggio dichiarato dal telefono deve coincidere con quello ricalcolato (tranne il quiz)
  if p_game.id <> 'quiz' and abs(coalesce(p_raw, -1) - v_score) > (case when p_game.id = 'memory' then 3 else 0 end) then
    v_rejected := true; v_notes := array_append(v_notes, 'punteggio_non_coerente');
  end if;
  if v_score > p_game.max_raw_score then
    v_rejected := true; v_notes := array_append(v_notes, 'oltre_il_massimo');
  end if;

  return jsonb_build_object(
    'status', case when v_rejected then 'rejected' when v_flagged then 'flagged' else 'valid' end,
    'score', v_score, 'notes', v_notes, 'correct', v_correct);
end;
$$;

-- ---------- RPC pubbliche ----------

-- Stato dei giochi (anche senza account): finestra, tentativi usati oggi, miglior punteggio
create or replace function public.get_games_state(p_token text default null)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_player players := case when p_token is null then null else _session_player(p_token) end;
  v_today date := _today();
begin
  return jsonb_build_object(
    'ok', true,
    'server_time', now(),
    'window', _window_state(),
    'open_from', _setting('games_open_from'),
    'open_until', _setting('games_open_until'),
    'attempts_per_day', _attempts_per_day(),
    'logged_in', v_player.id is not null,
    'unlimited', coalesce(v_player.role = 'staff', false),
    'games', (
      select jsonb_agg(jsonb_build_object(
        'id', g.id,
        'enabled', g.enabled,
        'attempts_used_today', case when v_player.id is null then null else
          (select count(*) from attempts a where a.player_id = v_player.id and a.game_id = g.id and a.day = v_today) end,
        'best', case when v_player.id is null then null else
          (select max(a.raw_score) from attempts a where a.player_id = v_player.id and a.game_id = g.id and a.status in ('valid', 'flagged')) end
      ) order by g.sort)
      from games g));
end;
$$;

-- Avvio di un tentativo: si conta SUBITO (chiudere l'app non lo restituisce)
create or replace function public.start_attempt(p_token text, p_game_id text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_player players := _session_player(p_token);
  v_game games;
  v_staff boolean;
  v_used int;
  v_per_day int := _attempts_per_day();
  v_window text := _window_state();
  v_qids int[];
  v_seen int[];
  v_attempt attempts;
begin
  if v_player.id is null then
    return jsonb_build_object('ok', false, 'error', 'NOT_LOGGED_IN');
  end if;
  v_staff := v_player.role = 'staff';
  select * into v_game from games where id = p_game_id;
  if v_game.id is null then
    return jsonb_build_object('ok', false, 'error', 'GAME_UNKNOWN');
  end if;
  if not v_staff then
    if not v_game.enabled then return jsonb_build_object('ok', false, 'error', 'GAME_DISABLED'); end if;
    if v_window = 'not_yet' then return jsonb_build_object('ok', false, 'error', 'GAMES_NOT_OPEN', 'open_from', _setting('games_open_from')); end if;
    if v_window = 'closed' then return jsonb_build_object('ok', false, 'error', 'GAMES_CLOSED'); end if;
  end if;

  -- Un avvio alla volta per giocatore e gioco (niente doppio tocco che supera il limite)
  perform pg_advisory_xact_lock(hashtext(v_player.id::text || ':' || p_game_id));
  select count(*) into v_used from attempts where player_id = v_player.id and game_id = p_game_id and day = _today();
  if not v_staff and v_used >= v_per_day then
    return jsonb_build_object('ok', false, 'error', 'NO_ATTEMPTS_LEFT', 'attempts_per_day', v_per_day);
  end if;

  if p_game_id = 'quiz' then
    -- 5 domande a caso, evitando quelle già capitate a questo giocatore (se ce ne sono abbastanza)
    select coalesce(array_agg(distinct q), '{}') into v_seen
    from attempts a, unnest(a.quiz_question_ids) as q where a.player_id = v_player.id and a.game_id = 'quiz';
    v_qids := array(select id from quiz_questions where active and not (id = any (v_seen)) order by random() limit 5);
    if coalesce(array_length(v_qids, 1), 0) < 5 then
      v_qids := array(select id from quiz_questions where active order by random() limit 5);
    end if;
    if coalesce(array_length(v_qids, 1), 0) = 0 then
      return jsonb_build_object('ok', false, 'error', 'QUIZ_EMPTY');
    end if;
  end if;

  insert into attempts (player_id, game_id, day, seed, quiz_question_ids)
  values (v_player.id, p_game_id, _today(), floor(random() * 4294967296)::bigint, v_qids)
  returning * into v_attempt;

  return jsonb_build_object(
    'ok', true,
    'attempt_id', v_attempt.id,
    'seed', v_attempt.seed,
    'unlimited', v_staff,
    'attempts_left', case when v_staff then null else v_per_day - v_used - 1 end,
    'attempts_per_day', v_per_day,
    -- Domande del quiz SENZA la risposta giusta
    'questions', case when p_game_id = 'quiz' then (
      select jsonb_agg(jsonb_build_object('id', q.id, 'text', q.text, 'options', to_jsonb(q.options))
                       order by array_position(v_qids, q.id))
      from quiz_questions q where q.id = any (v_qids)) end);
end;
$$;

-- Invio del punteggio. Basta l'id del tentativo (casuale, lo conosce solo chi l'ha avviato): così il
-- punteggio fatto offline arriva anche se nel frattempo la sessione è cambiata. Idempotente.
create or replace function public.submit_score(p_attempt_id uuid, p_raw_score int, p_stats jsonb, p_actions jsonb)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_attempt attempts;
  v_game games;
  v_check jsonb;
  v_best int;
begin
  select * into v_attempt from attempts where id = p_attempt_id for update;
  if v_attempt.id is null then
    return jsonb_build_object('ok', false, 'error', 'ATTEMPT_UNKNOWN');
  end if;
  select * into v_game from games where id = v_attempt.game_id;

  if v_attempt.submitted_at is null then
    v_check := _check_attempt(v_attempt, v_game, p_raw_score, p_stats, p_actions);
    update attempts set
      submitted_at = now(),
      client_score = p_raw_score,
      raw_score = (v_check ->> 'score')::int,
      stats = p_stats,
      actions = p_actions,
      status = v_check ->> 'status',
      check_notes = array(select jsonb_array_elements_text(v_check -> 'notes'))
    where id = v_attempt.id
    returning * into v_attempt;
  end if;

  select max(raw_score) into v_best from attempts
  where player_id = v_attempt.player_id and game_id = v_attempt.game_id and status in ('valid', 'flagged');

  return jsonb_build_object(
    'ok', true,
    'status', v_attempt.status,
    'raw_score', v_attempt.raw_score,
    'best', v_best,
    'correct', case when v_attempt.game_id = 'quiz' then
      (select count(*) from jsonb_array_elements(coalesce(v_attempt.stats -> 'answers', '[]')) a
       join quiz_questions q on q.id = (a ->> 'questionId')::int and q.correct_index = (a ->> 'choice')::int) end,
    'total', coalesce(array_length(v_attempt.quiz_question_ids, 1), 0));
end;
$$;

-- ---------- Permessi ----------

revoke execute on all functions in schema public from public, anon, authenticated;
grant execute on function public.check_nickname(text) to anon, authenticated;
grant execute on function public.register(text, text, text, uuid, text, text) to anon, authenticated;
grant execute on function public.login(text, text, uuid, text, text) to anon, authenticated;
grant execute on function public.logout(text) to anon, authenticated;
grant execute on function public.get_my_profile(text) to anon, authenticated;
grant execute on function public.get_games_state(text) to anon, authenticated;
grant execute on function public.start_attempt(text, text) to anon, authenticated;
grant execute on function public.submit_score(uuid, int, jsonb, jsonb) to anon, authenticated;

-- (Qui c'erano 15 domande di esempio con le risposte: tolte dal repository pubblico, D149.
-- Le domande si caricano dal pannello Admin o con npm run prod:copy.)
