-- =====================================================================================
-- 007 — Classifica (Tappa 6, D71)
--
-- - Totale di un giocatore = somma dei suoi MIGLIORI punteggi nei 4 giochi (tentativi 'valid' o 'flagged')
--   + i punti extra assegnati (tabella extra_points: per ora vuota, li assegnerà lo staff). Niente normalizzazione.
-- - La classifica NON si ricalcola da capo a ogni apertura: la tabella `leaderboard` tiene già migliori e totale
--   di ogni giocatore e viene aggiornata dal database solo per il giocatore che ha appena fatto un punteggio
--   (trigger). Leggerla è un semplice ordinamento sull'indice del totale.
-- - Pari punti = stessa posizione (es. due terzi, poi il quinto). Tra loro l'ordine è indifferente.
-- - "Live": ogni modifica fa avanzare un contatore di versione; il telefono chiede la classifica ogni pochi
--   secondi passando l'ultima versione vista e, se nulla è cambiato, riceve solo "invariata" (pochi byte).
-- - Esclusi dalla classifica gli account staff e quelli disattivati.
--
-- Come applicarla: Supabase → SQL Editor → incolla tutto il file → Run. Si può rieseguire.
-- =====================================================================================

-- ---------- Tabelle ----------

-- Punti extra dati a un giocatore durante le giornate (staff, Tappa 8; eventuali oggetti segreti, Tappa 7)
create table if not exists public.extra_points (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players (id) on delete cascade,
  points int not null,
  reason text not null,
  created_at timestamptz not null default now()
);
create index if not exists extra_points_player_idx on public.extra_points (player_id);

-- Riassunto per giocatore, sempre aggiornato dai trigger qui sotto
create table if not exists public.leaderboard (
  player_id uuid primary key references public.players (id) on delete cascade,
  best jsonb not null default '{}',       -- { "acchiappa": 1234, "quiz": 800, ... } migliori per gioco
  games_total int not null default 0,     -- somma dei migliori
  extra_total int not null default 0,     -- somma dei punti extra
  total int not null default 0,           -- games_total + extra_total
  updated_at timestamptz not null default now()
);
create index if not exists leaderboard_total_idx on public.leaderboard (total desc);

alter table public.extra_points enable row level security;
alter table public.leaderboard enable row level security;
revoke all on public.extra_points, public.leaderboard from anon, authenticated;

-- Versione della classifica: avanza a ogni cambiamento (per non rimandare la classifica se è uguale)
create sequence if not exists public.leaderboard_version_seq;
revoke all on sequence public.leaderboard_version_seq from anon, authenticated;

-- ---------- Aggiornamento del riassunto ----------

-- Ricalcola la riga di UN giocatore (migliori per gioco + extra) e fa avanzare la versione
create or replace function public._refresh_leaderboard(p_player_id uuid)
returns void language plpgsql volatile set search_path = public as $$
declare
  v_best jsonb;
  v_games int;
  v_extra int;
begin
  if not exists (select 1 from players where id = p_player_id) then
    return;
  end if;
  select coalesce(jsonb_object_agg(game_id, best), '{}'), coalesce(sum(best), 0)
    into v_best, v_games
  from (
    select game_id, max(raw_score) as best
    from attempts
    where player_id = p_player_id and status in ('valid', 'flagged') and raw_score is not null
    group by game_id
  ) b;
  select coalesce(sum(points), 0) into v_extra from extra_points where player_id = p_player_id;
  -- Nessun punto e nessuna riga: niente da fare (es. un tentativo appena avviato)
  if v_games + v_extra = 0 and not exists (select 1 from leaderboard where player_id = p_player_id) then
    return;
  end if;

  insert into leaderboard (player_id, best, games_total, extra_total, total, updated_at)
  values (p_player_id, v_best, v_games, v_extra, v_games + v_extra, now())
  on conflict (player_id) do update set
    best = excluded.best, games_total = excluded.games_total, extra_total = excluded.extra_total,
    total = excluded.total, updated_at = now()
  where leaderboard.best is distinct from excluded.best or leaderboard.extra_total is distinct from excluded.extra_total;

  if found then
    perform nextval('leaderboard_version_seq');
  end if;
end;
$$;

create or replace function public._leaderboard_on_attempt()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform _refresh_leaderboard(coalesce(new.player_id, old.player_id));
  return null;
end;
$$;

drop trigger if exists attempts_leaderboard on public.attempts;
create trigger attempts_leaderboard
after insert or update of status, raw_score or delete on public.attempts
for each row execute function public._leaderboard_on_attempt();

drop trigger if exists extra_points_leaderboard on public.extra_points;
create trigger extra_points_leaderboard
after insert or update or delete on public.extra_points
for each row execute function public._leaderboard_on_attempt();

-- Cambi di nickname, personaggio, ruolo o disattivazione: la classifica mostrata cambia
create or replace function public._leaderboard_on_player()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform nextval('leaderboard_version_seq');
  return null;
end;
$$;

drop trigger if exists players_leaderboard on public.players;
create trigger players_leaderboard
after update of nickname, avatar, role, disabled or delete on public.players
for each row execute function public._leaderboard_on_player();

-- ---------- Lettura ----------

-- Giocatori che compaiono in classifica (niente staff né disattivati, almeno 1 punto)
create or replace function public._leaderboard_rows()
returns table (player_id uuid, nickname text, avatar text, total int, best jsonb, extra_total int)
language sql stable set search_path = public as $$
  select l.player_id, p.nickname, p.avatar, l.total, l.best, l.extra_total
  from leaderboard l
  join players p on p.id = l.player_id
  where p.role = 'player' and not p.disabled and l.total > 0;
$$;

-- Posizione con pari merito: 1 + quanti hanno più punti
create or replace function public._leaderboard_position(p_total int)
returns int language sql stable set search_path = public as $$
  select 1 + count(*)::int from _leaderboard_rows() r where r.total > p_total;
$$;

-- Scheda di un giocatore (la stessa del profilo): personaggio, punti totali, posizione, migliori per gioco, extra
create or replace function public._player_card(p_player_id uuid)
returns jsonb language sql stable set search_path = public as $$
  select jsonb_build_object(
    'nickname', p.nickname,
    'avatar', p.avatar,
    'total', coalesce(l.total, 0),
    'position', case when coalesce(l.total, 0) > 0 and p.role = 'player' and not p.disabled
                     then _leaderboard_position(l.total) end,
    'best', coalesce(l.best, '{}'),
    'extra_total', coalesce(l.extra_total, 0),
    'players', (select count(*) from _leaderboard_rows()))
  from players p
  left join leaderboard l on l.player_id = p.id
  where p.id = p_player_id;
$$;

-- Classifica: primi 20 (con i pari merito del 20°) + la riga di chi la guarda.
-- p_version = ultima versione ricevuta: se non è cambiato nulla risponde solo { unchanged: true }.
create or replace function public.get_leaderboard(p_token text default null, p_version bigint default null)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_version bigint := (select last_value from leaderboard_version_seq);
  v_player players := case when p_token is null then null else _session_player(p_token) end;
  v_me jsonb;
begin
  if p_version is not null and p_version = v_version then
    return jsonb_build_object('ok', true, 'unchanged', true, 'version', v_version, 'window', _window_state());
  end if;
  if v_player.id is not null then
    v_me := _player_card(v_player.id);
  end if;
  return jsonb_build_object(
    'ok', true,
    'version', v_version,
    'window', _window_state(),
    'players', (select count(*) from _leaderboard_rows()),
    'top', coalesce((
      select jsonb_agg(jsonb_build_object('position', r.position, 'nickname', r.nickname, 'avatar', r.avatar, 'total', r.total)
                       order by r.position, lower(r.nickname))
      from (
        select x.nickname, x.avatar, x.total, rank() over (order by x.total desc)::int as position
        from _leaderboard_rows() x
      ) r
      where r.position <= 20), '[]'),
    'me', v_me);
end;
$$;

-- Scheda di un altro giocatore (tocco sulla classifica)
create or replace function public.get_player_card(p_nickname text)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_id uuid;
begin
  select id into v_id from players
  where lower(nickname) = lower(trim(p_nickname)) and role = 'player' and not disabled;
  if v_id is null then
    return jsonb_build_object('ok', false, 'error', 'NOT_FOUND');
  end if;
  return jsonb_build_object('ok', true, 'player', _player_card(v_id));
end;
$$;

-- ---------- Riassunto iniziale dei punteggi già fatti ----------

select _refresh_leaderboard(id) from public.players;

-- ---------- Permessi ----------

revoke execute on function public._refresh_leaderboard(uuid), public._leaderboard_on_attempt(), public._leaderboard_on_player(),
  public._leaderboard_rows(), public._leaderboard_position(int), public._player_card(uuid)
  from public, anon, authenticated;
revoke execute on function public.get_leaderboard(text, bigint), public.get_player_card(text) from public;
grant execute on function public.get_leaderboard(text, bigint) to anon, authenticated;
grant execute on function public.get_player_card(text) to anon, authenticated;
