-- =====================================================================================
-- 008 — Pannello staff (Tappa 8, D73)
--
-- Tutte le funzioni staff_* chiedono la chiave di sessione e controllano SUL SERVER che l'account sia staff
-- (ruolo 'staff', non disattivato): un giocatore normale che le chiama riceve solo NOT_STAFF.
-- Ogni azione che cambia qualcosa finisce in staff_log (chi, cosa, quando).
-- Gli account staff si creano a mano (vedi docs/SUPABASE.md) ed entrano con nickname + password
-- usando la normale funzione login.
--
-- Come applicarla: Supabase → SQL Editor → incolla tutto il file → Run. Si può rieseguire.
-- =====================================================================================

create table if not exists public.staff_log (
  id bigint generated by default as identity primary key,
  staff_nickname text not null,
  action text not null,
  target text,
  details jsonb,
  created_at timestamptz not null default now()
);
create index if not exists staff_log_created_idx on public.staff_log (created_at desc);
alter table public.staff_log enable row level security;
revoke all on public.staff_log from anon, authenticated;

-- ---------- Aiuti ----------

-- Account staff della sessione (null se non è staff)
create or replace function public._staff_player(p_token text)
returns public.players language plpgsql volatile security definer set search_path = public as $$
declare
  v_player players := _session_player(p_token);
begin
  if v_player.id is null or v_player.role <> 'staff' then
    return null;
  end if;
  return v_player;
end;
$$;

create or replace function public._staff_denied()
returns jsonb language sql immutable as $$
  select jsonb_build_object('ok', false, 'error', 'NOT_STAFF');
$$;

create or replace function public._staff_log(p_staff players, p_action text, p_target text, p_details jsonb default null)
returns void language sql volatile security definer set search_path = public as $$
  insert into staff_log (staff_nickname, action, target, details) values (p_staff.nickname, p_action, p_target, p_details);
$$;

-- Giocatore (non staff) dal nickname
create or replace function public._find_player(p_nickname text)
returns public.players language sql stable security definer set search_path = public as $$
  select * from players where lower(nickname) = lower(trim(coalesce(p_nickname, ''))) and role = 'player';
$$;

-- ---------- Giocatori ----------

-- Ricerca per nickname (vuota = ultimi registrati). Max 30 risultati, prima la corrispondenza esatta.
create or replace function public.staff_search_players(p_token text, p_query text default '')
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
  v_q text := lower(trim(coalesce(p_query, '')));
begin
  if v_staff.id is null then return _staff_denied(); end if;
  return jsonb_build_object('ok', true, 'players', coalesce((
    select jsonb_agg(jsonb_build_object(
      'nickname', p.nickname, 'avatar', p.avatar, 'role', p.role, 'disabled', p.disabled,
      'total', coalesce(l.total, 0), 'created_at', p.created_at) order by x.exact desc, x.created_at desc)
    from (
      select p.id, (lower(p.nickname) = v_q) as exact, p.created_at
      from players p
      where v_q = '' or strpos(lower(p.nickname), v_q) > 0
      order by (lower(p.nickname) = v_q) desc, p.created_at desc
      limit 30
    ) x
    join players p on p.id = x.id
    left join leaderboard l on l.player_id = p.id), '[]'));
end;
$$;

-- Scheda completa di un giocatore per lo staff
create or replace function public.staff_player_detail(p_token text, p_nickname text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
  v_player players;
begin
  if v_staff.id is null then return _staff_denied(); end if;
  select * into v_player from players where lower(nickname) = lower(trim(coalesce(p_nickname, '')));
  if v_player.id is null then
    return jsonb_build_object('ok', false, 'error', 'NOT_FOUND');
  end if;
  return jsonb_build_object('ok', true, 'player', jsonb_build_object(
    'nickname', v_player.nickname,
    'avatar', v_player.avatar,
    'role', v_player.role,
    'disabled', v_player.disabled,
    'created_at', v_player.created_at,
    'card', _player_card(v_player.id),
    -- Telefoni con cui si è registrato (il codice "EF27-B764" lo calcola l'app dal device_id)
    'devices', coalesce((
      select jsonb_agg(jsonb_build_object(
        'device_id', d.device_id, 'created_at', d.created_at, 'user_agent', d.user_agent,
        'same_fingerprint', (select count(distinct d2.player_id) from devices d2
                             where d2.fingerprint = d.fingerprint and d2.player_id <> v_player.id))
        order by d.created_at)
      from devices d where d.player_id = v_player.id), '[]'),
    -- Telefoni da cui è entrato (sessioni ancora valide)
    'sessions', coalesce((
      select jsonb_agg(jsonb_build_object('device_id', s.device_id, 'last_seen_at', s.last_seen_at, 'user_agent', s.user_agent)
        order by s.last_seen_at desc)
      from sessions s where s.player_id = v_player.id and s.expires_at > now()), '[]'),
    'extra_points', coalesce((
      select jsonb_agg(jsonb_build_object('id', e.id, 'points', e.points, 'reason', e.reason, 'created_at', e.created_at)
        order by e.created_at desc)
      from extra_points e where e.player_id = v_player.id), '[]'),
    'games', coalesce((
      select jsonb_agg(jsonb_build_object(
        'game_id', g.id, 'name', g.name,
        'best', (select max(a.raw_score) from attempts a where a.player_id = v_player.id and a.game_id = g.id and a.status in ('valid', 'flagged')),
        'valid', (select count(*) from attempts a where a.player_id = v_player.id and a.game_id = g.id and a.status = 'valid'),
        'flagged', (select count(*) from attempts a where a.player_id = v_player.id and a.game_id = g.id and a.status = 'flagged'),
        'rejected', (select count(*) from attempts a where a.player_id = v_player.id and a.game_id = g.id and a.status = 'rejected'),
        'pending', (select count(*) from attempts a where a.player_id = v_player.id and a.game_id = g.id and a.status = 'pending'))
        order by g.sort)
      from games g), '[]'),
    'login_failures', (select count(*) from login_failures f
                       where f.nickname_lower = lower(v_player.nickname) and f.failed_at > now() - interval '15 minutes')));
end;
$$;

-- Nuovo PIN (dopo aver controllato di persona il codice del telefono). Chiude tutte le sessioni e sblocca l'accesso.
create or replace function public.staff_reset_pin(p_token text, p_nickname text, p_new_pin text)
returns jsonb language plpgsql volatile security definer set search_path = public, extensions as $$
declare
  v_staff players := _staff_player(p_token);
  v_player players := _find_player(p_nickname);
begin
  if v_staff.id is null then return _staff_denied(); end if;
  if v_player.id is null then return jsonb_build_object('ok', false, 'error', 'NOT_FOUND'); end if;
  if p_new_pin is null or p_new_pin !~ '^[0-9]{4}$' then
    return jsonb_build_object('ok', false, 'error', 'PIN_INVALID');
  end if;
  update players set pin_hash = extensions.crypt(p_new_pin, extensions.gen_salt('bf', 8)) where id = v_player.id;
  delete from sessions where player_id = v_player.id;
  delete from login_failures where nickname_lower = lower(v_player.nickname);
  perform _staff_log(v_staff, 'reset_pin', v_player.nickname);
  return jsonb_build_object('ok', true);
end;
$$;

-- Disattiva / riattiva (un account disattivato non entra e non compare in classifica; il telefono resta legato)
create or replace function public.staff_set_disabled(p_token text, p_nickname text, p_disabled boolean)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
  v_player players := _find_player(p_nickname);
begin
  if v_staff.id is null then return _staff_denied(); end if;
  if v_player.id is null then return jsonb_build_object('ok', false, 'error', 'NOT_FOUND'); end if;
  update players set disabled = coalesce(p_disabled, false) where id = v_player.id;
  if p_disabled then
    delete from sessions where player_id = v_player.id;
  end if;
  perform _staff_log(v_staff, case when p_disabled then 'disable' else 'enable' end, v_player.nickname);
  return jsonb_build_object('ok', true);
end;
$$;

-- Cancella DEFINITIVAMENTE (account, punteggi, sessioni; il telefono torna libero). Serve riscrivere il nickname.
create or replace function public.staff_delete_player(p_token text, p_nickname text, p_confirm text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
  v_player players := _find_player(p_nickname);
begin
  if v_staff.id is null then return _staff_denied(); end if;
  if v_player.id is null then return jsonb_build_object('ok', false, 'error', 'NOT_FOUND'); end if;
  if p_confirm is null or lower(trim(p_confirm)) <> lower(v_player.nickname) then
    return jsonb_build_object('ok', false, 'error', 'CONFIRM_MISMATCH');
  end if;
  perform _staff_log(v_staff, 'delete', v_player.nickname,
    jsonb_build_object('total', (select total from leaderboard where player_id = v_player.id)));
  delete from players where id = v_player.id;   -- dispositivi, sessioni, tentativi, punti extra: a cascata
  return jsonb_build_object('ok', true);
end;
$$;

-- Punti extra (+ o −) con motivo
create or replace function public.staff_add_extra_points(p_token text, p_nickname text, p_points int, p_reason text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
  v_player players := _find_player(p_nickname);
begin
  if v_staff.id is null then return _staff_denied(); end if;
  if v_player.id is null then return jsonb_build_object('ok', false, 'error', 'NOT_FOUND'); end if;
  if p_points is null or p_points = 0 or abs(p_points) > 10000 then
    return jsonb_build_object('ok', false, 'error', 'POINTS_INVALID');
  end if;
  if length(trim(coalesce(p_reason, ''))) < 2 then
    return jsonb_build_object('ok', false, 'error', 'REASON_REQUIRED');
  end if;
  insert into extra_points (player_id, points, reason) values (v_player.id, p_points, left(trim(p_reason), 200));
  perform _staff_log(v_staff, 'extra_points', v_player.nickname, jsonb_build_object('points', p_points, 'reason', trim(p_reason)));
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.staff_delete_extra_points(p_token text, p_id bigint)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
  v_row extra_points;
begin
  if v_staff.id is null then return _staff_denied(); end if;
  delete from extra_points where id = p_id returning * into v_row;
  if v_row.id is null then return jsonb_build_object('ok', false, 'error', 'NOT_FOUND'); end if;
  perform _staff_log(v_staff, 'extra_points_removed', (select nickname from players where id = v_row.player_id),
    jsonb_build_object('points', v_row.points, 'reason', v_row.reason));
  return jsonb_build_object('ok', true);
end;
$$;

-- ---------- Partite da controllare ----------

-- 'flagged' = contate ma segnalate (possibili bot); 'rejected' = escluse in automatico
create or replace function public.staff_review_list(p_token text, p_status text default 'flagged')
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
begin
  if v_staff.id is null then return _staff_denied(); end if;
  if p_status not in ('flagged', 'rejected') then
    return jsonb_build_object('ok', false, 'error', 'STATUS_INVALID');
  end if;
  return jsonb_build_object('ok', true, 'attempts', coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', a.id, 'nickname', p.nickname, 'game_id', a.game_id, 'status', a.status,
      'raw_score', a.raw_score, 'client_score', a.client_score, 'notes', a.check_notes, 'submitted_at', a.submitted_at)
      order by a.submitted_at desc)
    from (select * from attempts where status = p_status order by submitted_at desc nulls last limit 200) a
    join players p on p.id = a.player_id), '[]'));
end;
$$;

-- Approva (valid) o scarta (rejected) una partita segnalata; rimette (valid) una partita esclusa
create or replace function public.staff_set_attempt_status(p_token text, p_attempt_id uuid, p_status text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
  v_attempt attempts;
begin
  if v_staff.id is null then return _staff_denied(); end if;
  if p_status not in ('valid', 'rejected') then
    return jsonb_build_object('ok', false, 'error', 'STATUS_INVALID');
  end if;
  select * into v_attempt from attempts where id = p_attempt_id for update;
  if v_attempt.id is null or v_attempt.status not in ('flagged', 'rejected', 'valid') then
    return jsonb_build_object('ok', false, 'error', 'NOT_FOUND');
  end if;
  update attempts set status = p_status,
    check_notes = array_append(check_notes, case when p_status = 'valid' then 'approvata_da_staff' else 'scartata_da_staff' end)
  where id = v_attempt.id;
  perform _staff_log(v_staff, 'attempt_' || p_status, (select nickname from players where id = v_attempt.player_id),
    jsonb_build_object('attempt_id', v_attempt.id, 'game_id', v_attempt.game_id, 'from', v_attempt.status, 'raw_score', v_attempt.raw_score));
  return jsonb_build_object('ok', true);
end;
$$;

-- ---------- Telefoni sospetti ----------

-- Stessa impronta tecnica su più account. Solo indicativo: telefoni uguali (stesso modello e browser)
-- possono avere la stessa impronta anche se sono di persone diverse.
create or replace function public.staff_suspicious_devices(p_token text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
begin
  if v_staff.id is null then return _staff_denied(); end if;
  return jsonb_build_object('ok', true, 'groups', coalesce((
    select jsonb_agg(jsonb_build_object('fingerprint', left(g.fingerprint, 8), 'count', g.n, 'nicknames', g.nicknames) order by g.n desc)
    from (
      select d.fingerprint, count(distinct d.player_id) as n,
             jsonb_agg(distinct p.nickname) as nicknames
      from devices d join players p on p.id = d.player_id
      where d.fingerprint is not null and p.role = 'player'
      group by d.fingerprint
      having count(distinct d.player_id) >= 2
      order by count(distinct d.player_id) desc
      limit 50
    ) g), '[]'));
end;
$$;

-- ---------- Impostazioni ----------

create or replace function public.staff_get_settings(p_token text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
begin
  if v_staff.id is null then return _staff_denied(); end if;
  return jsonb_build_object('ok', true,
    'attempts_per_day', _attempts_per_day(),
    'attempts_reset_hour', coalesce((_setting('attempts_reset_hour') #>> '{}')::int, 0),
    'games_open_from', _setting('games_open_from'),
    'games_open_until', _setting('games_open_until'),
    'window', _window_state(),
    'games', (select jsonb_agg(jsonb_build_object('id', id, 'name', name, 'enabled', enabled) order by sort) from games));
end;
$$;

-- p_values: { attempts_per_day?, attempts_reset_hour?, games_open_from?, games_open_until?, games?: { id: true|false } }
-- Date in formato ISO con fuso (es. "2026-10-17T15:00:00+02:00"), null = nessun limite.
create or replace function public.staff_update_settings(p_token text, p_values jsonb)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
  v_n int;
  v_key text;
  v_game record;
begin
  if v_staff.id is null then return _staff_denied(); end if;
  if p_values is null or jsonb_typeof(p_values) <> 'object' then
    return jsonb_build_object('ok', false, 'error', 'VALUES_INVALID');
  end if;

  if p_values ? 'attempts_per_day' then
    v_n := (p_values ->> 'attempts_per_day')::int;
    if v_n is null or v_n < 1 or v_n > 50 then return jsonb_build_object('ok', false, 'error', 'ATTEMPTS_INVALID'); end if;
    update settings set value = to_jsonb(v_n) where key = 'attempts_per_day';
  end if;
  if p_values ? 'attempts_reset_hour' then
    v_n := (p_values ->> 'attempts_reset_hour')::int;
    if v_n is null or v_n < 0 or v_n > 23 then return jsonb_build_object('ok', false, 'error', 'HOUR_INVALID'); end if;
    insert into settings (key, value) values ('attempts_reset_hour', to_jsonb(v_n))
    on conflict (key) do update set value = excluded.value;
  end if;
  foreach v_key in array array['games_open_from', 'games_open_until'] loop
    if p_values ? v_key then
      if jsonb_typeof(p_values -> v_key) = 'null' then
        update settings set value = 'null' where key = v_key;
      else
        -- valida la data (errore se non è una data)
        perform (p_values ->> v_key)::timestamptz;
        update settings set value = to_jsonb(p_values ->> v_key) where key = v_key;
      end if;
    end if;
  end loop;
  if jsonb_typeof(p_values -> 'games') = 'object' then
    for v_game in select key, value from jsonb_each(p_values -> 'games') loop
      update games set enabled = (v_game.value)::text::boolean where id = v_game.key;
    end loop;
  end if;

  perform _staff_log(v_staff, 'settings', null, p_values);
  perform nextval('leaderboard_version_seq'); -- "Classifica finale" può cambiare
  return jsonb_build_object('ok', true);
exception when invalid_datetime_format or datetime_field_overflow or invalid_text_representation then
  return jsonb_build_object('ok', false, 'error', 'DATE_INVALID');
end;
$$;

-- ---------- Classifica completa ----------

create or replace function public.staff_leaderboard(p_token text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
begin
  if v_staff.id is null then return _staff_denied(); end if;
  return jsonb_build_object('ok', true, 'window', _window_state(), 'rows', coalesce((
    select jsonb_agg(jsonb_build_object('position', r.position, 'nickname', r.nickname, 'total', r.total,
                                        'best', r.best, 'extra_total', r.extra_total)
                     order by r.position, lower(r.nickname))
    from (select x.*, rank() over (order by x.total desc)::int as position from _leaderboard_rows() x) r), '[]'));
end;
$$;

-- Ultime azioni dello staff
create or replace function public.staff_log_list(p_token text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
begin
  if v_staff.id is null then return _staff_denied(); end if;
  return jsonb_build_object('ok', true, 'entries', coalesce((
    select jsonb_agg(jsonb_build_object('staff', l.staff_nickname, 'action', l.action, 'target', l.target,
                                        'details', l.details, 'created_at', l.created_at) order by l.created_at desc)
    from (select * from staff_log order by created_at desc limit 100) l), '[]'));
end;
$$;

-- ---------- Permessi ----------

revoke execute on function public._staff_player(text), public._staff_denied(), public._staff_log(players, text, text, jsonb),
  public._find_player(text) from public, anon, authenticated;

do $$
declare
  f text;
begin
  foreach f in array array[
    'staff_search_players(text, text)', 'staff_player_detail(text, text)', 'staff_reset_pin(text, text, text)',
    'staff_set_disabled(text, text, boolean)', 'staff_delete_player(text, text, text)',
    'staff_add_extra_points(text, text, int, text)', 'staff_delete_extra_points(text, bigint)',
    'staff_review_list(text, text)', 'staff_set_attempt_status(text, uuid, text)', 'staff_suspicious_devices(text)',
    'staff_get_settings(text)', 'staff_update_settings(text, jsonb)', 'staff_leaderboard(text)', 'staff_log_list(text)'
  ] loop
    execute format('revoke execute on function public.%s from public', f);
    execute format('grant execute on function public.%s to anon, authenticated', f);
  end loop;
end $$;
