-- =====================================================================================
-- 012 — Registro degli accessi (D79)
--
-- Ogni accesso (registrazione o login) crea una sessione; le sessioni però spariscono quando si esce.
-- Qui ne resta traccia: telefono, quando, browser. Lo staff vede gli ultimi 20 accessi di un giocatore.
--
-- Come applicarla: Supabase → SQL Editor → incolla tutto il file → Run. Si può rieseguire.
-- =====================================================================================

create table if not exists public.access_log (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players (id) on delete cascade,
  device_id uuid,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists access_log_player_idx on public.access_log (player_id, created_at desc);
alter table public.access_log enable row level security;
revoke all on public.access_log from anon, authenticated;

-- Accessi già fatti (dalle sessioni ancora presenti), solo la prima volta
insert into public.access_log (player_id, device_id, user_agent, created_at)
select player_id, device_id, user_agent, created_at from public.sessions
where not exists (select 1 from public.access_log);

-- Ogni nuova sessione = un accesso
create or replace function public._log_access()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into access_log (player_id, device_id, user_agent, created_at)
  values (new.player_id, new.device_id, new.user_agent, new.created_at);
  return null;
end;
$$;

drop trigger if exists sessions_access_log on public.sessions;
create trigger sessions_access_log after insert on public.sessions
for each row execute function public._log_access();

-- Ultimi 20 accessi di un giocatore (per lo staff)
create or replace function public.staff_player_accesses(p_token text, p_nickname text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_staff players := _staff_player(p_token);
  v_player players;
begin
  if v_staff.id is null then return _staff_denied(); end if;
  select * into v_player from players where lower(nickname) = lower(trim(coalesce(p_nickname, '')));
  if v_player.id is null then return jsonb_build_object('ok', false, 'error', 'NOT_FOUND'); end if;
  return jsonb_build_object('ok', true, 'accesses', coalesce((
    select jsonb_agg(jsonb_build_object('device_id', a.device_id, 'user_agent', a.user_agent, 'created_at', a.created_at,
                                        'registration', exists (select 1 from devices d where d.device_id = a.device_id and d.player_id = v_player.id))
                     order by a.created_at desc)
    from (select * from access_log where player_id = v_player.id order by created_at desc limit 20) a), '[]'));
end;
$$;

revoke execute on function public._log_access() from public, anon, authenticated;
revoke execute on function public.staff_player_accesses(text, text) from public;
grant execute on function public.staff_player_accesses(text, text) to anon, authenticated;
